### ISSUE TITLE
rewrite using eloquent. orm 

### ISSUE THREAD

**Issue by bazavlukd** [NazikD/Donation_Platform#13]
https://github.com/NazikD/Donation_Platform/blob/783d451457ece86c8b5b83a842cc5c85c17fdbd9/app/Http/Controllers/DashboardController.php#L29

```
$maxDonator = Donator::max('amount');
```

**Comment by bazavlukd** [comment]
or

$maxDonator = Donator::select(DB::raw("max(amount) as amountDonator"))
            ->get();

**Comment by NazikD** [comment]
corrected
